---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  namespace: canary
  labels:
    app: canary-nginx
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: canary-nginx
  template:
    metadata:
      labels:
        app: canary-nginx
        version: v1
    spec:
      containers:
      - name: nginx
        imagePullPolicy: IfNotPresent
        image: nginx:1.25.4
        ports:
        - containerPort: 80
        env:
          - name: "PORT"
            valueFrom:
              configMapKeyRef:
                name: canary-nginx-configmap-1
                key: nginx-http-port
        resources:
          limits:
            cpu: "0.1"
            memory: "128Mi"
        volumeMounts:
        - name: nginx-config
          mountPath: "/etc/nginx"
          readOnly: true
        - name: nginx-site
          mountPath: "/var/www/html/canary-nginx"
          readOnly: true
      volumes:
      - name: nginx-config
        configMap:
          name: canary-nginx-configmap-1
          items:
          - key: nginx-conf
            path: nginx.conf
      - name: nginx-site
        configMap:
          name: canary-nginx-configmap-1
          items:
          - key: nginx-site
            path: index.html