apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: canary-gateway
  namespace: canary
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "istio.canary.example.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: canary-vs
  namespace: canary
spec:
  hosts:
  - "istio.canary.example.com"
  gateways:
  - canary-gateway
  http:
    - route:
      - destination:
          host: canary-nginx-service.canary.svc.cluster.local
          subset: v1
          port:
            number: 9001
        weight: 10
      - destination:
          host: canary-nginx-service.canary.svc.cluster.local
          subset: v2
          port:
            number: 9001
        weight: 90
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canary-dr
  namespace: canary
spec:
  host: canary-nginx-service.canary.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2